spring:
  cloud:
    config:
      server:
        git:
          clone-on-start: true
          # We don't want cloned repo to be removed from /tmp
          # See https://cloud.spring.io/spring-cloud-config/reference/html/#_version_control_backend_filesystem_use
          basedir: git-cache/cache
  security:
    user:
      name: admin
      password: admin